name: Publish to PyPI

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  - build_publish
   - name: Build package
        run: poetry build

      - name: Publish package to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: poetry publish --username __token__ --password $POETRY_PYPI_TOKEN_PYPI